accounts/urls.py
from django.urls import path

from .views import (
    UserPasswordResetDoneView, UserRegistView, UserCreateDoneView, UserCreateComplateView, UserLoginView,
    UserLogoutView, UserPasswordResetView, UserPasswordResetConfirmView, UserPasswordResetCompleteView, 
    UserEditView
)

app_name = 'accounts'

urlpatterns = [
    path('user_regist', UserRegistView.as_view(), name='user_regist'),
    path('user_create_done', UserCreateDoneView.as_view(), name='user_create_done'),
    path('user_create_complete/<token>', UserCreateComplateView.as_view(), name='user_create_complete'),
    path('user_login', UserLoginView.as_view(), name='user_login'),
    path('user_logout', UserLogoutView.as_view(), name='user_logout'),
    path('user_password_reset', UserPasswordResetView.as_view(), name='user_password_reset'),
    path('user_password_reset_done', UserPasswordResetDoneView.as_view(), name='user_password_reset_done'),
    path('user_password_reset_confirm/<uidb64>/<token>', UserPasswordResetConfirmView.as_view(), name='user_password_reset_confirm'),
    path('user_password_reset_complete', UserPasswordResetCompleteView.as_view(), name='user_password_reset_complete'),
    path('user_edit/<int:pk>', UserEditView.as_view(), name='user_edit'),
]

taskmanagement_project/urls.py
from django.contrib import admin
from django.urls import path, include

from taskmanagement import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('taskmanagement/', include('taskmanagement.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = views.page_not_found
handler500 = views.server_error

accounts/models.py
from email.errors import CloseBoundaryNotFoundDefect
from django.db import models
from django.core.mail import send_mail
from django.utils import timezone

from django.contrib.auth.models import (
    AbstractBaseUser, PermissionsMixin, UserManager
)


class UserManager(UserManager):

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email mut be set')
        user = self.model(
            email=email,
            **extra_fields,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_active', False)
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)


    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create_user(email, password, **extra_fields)


class Users(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    country = models.CharField(max_length=50)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    create_at = models.DateTimeField(default=timezone.now)
    update_at = models.DateTimeField(default=timezone.now)

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

accounts/forms.py
import pytz

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.password_validation import validate_password

from django.contrib.auth.forms import (
    AuthenticationForm, ReadOnlyPasswordHashField, PasswordResetForm, 
    SetPasswordForm
)


User = get_user_model()

COUNTRY_CHOICES = tuple([(country, country) for country in pytz.common_timezones])


class UserCreationForm(forms.ModelForm):
    country = forms.ChoiceField(label='TimeZone', choices=COUNTRY_CHOICES)
    password = forms.CharField(label='Password', widget=forms.PasswordInput())
    confirm_password = forms.CharField(label='Confirm Password', widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('email', 'password', 'confirm_password', 'country')

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['placeholder'] = str(field.label) + '*'
            field.widget.attrs['class'] = 'form-control'
    
    def clean_email(self):
        email = self.cleaned_data['email']
        at_position = email.find('@') + 1
        email = email[:at_position] + email[at_position:].lower()
        User.objects.filter(email=email, is_active=False).delete()
        return email

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data['password']
        confirm_password = cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('passwords do not match')

    def save(self, commit=False):
        user = super().save(commit=False)
        user.is_active = False
        validate_password(self.cleaned_data['password'], user)
        user.set_password(self.cleaned_data['password'])
        user.save()
        return user


class UserLoginForm(AuthenticationForm):
    username = forms.EmailField(label='Email')
    password = forms.CharField(label='Password', widget=forms.PasswordInput())
    remember = forms.BooleanField(label='Remember Me', required=False)

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['class'] = 'form-control'
        self.fields['remember'].widget.attrs['class'] = 'form-remember'
        self.fields['username'].widget.attrs['placeholder'] = str(self.fields['username'].label) + '*'
        self.fields['password'].widget.attrs['placeholder'] = str(self.fields['password'].label) + '*'


class UserPasswordResetForm(PasswordResetForm):

    def __init__(self, *args, **kwargs):
        super(UserPasswordResetForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
        

class UserSetPasswordForm(SetPasswordForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'



# Useredit Form (Admin Page)
class UserChangeForm(forms.ModelForm):
    country = forms.ChoiceField(choices=COUNTRY_CHOICES)
    create_at = forms.DateTimeField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    password = ReadOnlyPasswordHashField()

    class Meta:
        models = User
        fields = ('email', 'password', 'country', 'is_staff', 'is_active', 'is_superuser', 'create_at', 'update_at')

    def clean_password(self):
        return self.initial['password']


class UserEditForm(forms.ModelForm):
    country = forms.ChoiceField(label='TimeZone', choices=COUNTRY_CHOICES)

    class Meta:
        model = User
        fields = ('email', 'country')

    def __init__(self, *args, **kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['placeholder'] = str(field.label) + '*'
            field.widget.attrs['class'] = 'form-control'
    
    def clean_email(self):
        email = self.cleaned_data['email']
        at_position = email.find('@') + 1
        email = email[:at_position] + email[at_position:].lower()
        User.objects.filter(email=email, is_active=False).delete()
        return email

accounts/views.py
from django.core.exceptions import ValidationError
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.template.loader import render_to_string
from django.urls.base import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from django.shortcuts import render, redirect

from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.views import (
    LoginView, LogoutView,PasswordResetView, PasswordResetDoneView, 
    PasswordResetConfirmView, PasswordResetCompleteView
)

from .forms import (
    UserCreationForm, UserLoginForm, UserPasswordResetForm, UserSetPasswordForm, 
    UserEditForm
)

from taskmanagement.models import Memo



User = get_user_model()


class UserRegistView(CreateView):
    template_name = 'accounts/user_regist.html'
    form_class = UserCreationForm


    def form_valid(self, form):
        try:
            user = form.save()
        except ValidationError as e:
            form.add_error('password', e)
            return render(self.request, 'accounts/user_regist.html', context={
                'form': form
            })

        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk), 
            'user': user,
        }

        subject = render_to_string('accounts/mail_template/regist/subject.txt', context)
        message = render_to_string('accounts/mail_template/regist/message.txt', context)
        from_email = settings.DEFAULT_FROM_EMAIL

        user.email_user(subject, message, from_email)
        return redirect('accounts:user_create_done')

        

class UserCreateDoneView(TemplateView):
    template_name = 'accounts/user_create_done.html'


class UserCreateComplateView(TemplateView):
    template_name = 'accounts/user_create_complate.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*1)

    def get(self, request, **kwargs):
        error_message = []
        token = kwargs.get('token')

        try:
            user_pk = loads(token, max_age=self.timeout_seconds)
        
        except SignatureExpired:
            error_message.append('Expired. Please sign up again.')
        
        except BadSignature:
            error_message.append('Wrong URL. Please confirm your URL.')

        else:
            user = User.objects.get(pk=user_pk)
            if user:
                user.is_active = True
                user.save()
                Memo.objects.create(
                    memo=None,
                    user=user,
                )
                return super().get(request, **kwargs)
        
        return render(request, 'accounts/user_create_failed.html', context={
            'error_message': error_message,
        })


class UserLoginView(LoginView):
    template_name = 'accounts/user_login.html'
    authentication_form = UserLoginForm

    def form_valid(self, form):
        remember = form.cleaned_data['remember']
        if remember:
            self.request.session.set_expiry(1209600)
        return super().form_valid(form)


class UserLogoutView(LogoutView):
    pass


class UserPasswordResetView(PasswordResetView):
    template_name = 'accounts/user_password_reset.html'
    form_class = UserPasswordResetForm
    subject_template_name = 'accounts/mail_template/password_reset/subject.txt'
    email_template_name = 'accounts/mail_template/password_reset/message.txt'
    success_url = reverse_lazy('accounts:user_password_reset_done')


class UserPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'accounts/user_password_reset_done.html'


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'accounts/user_password_reset_confirm.html'
    form_class = UserSetPasswordForm
    success_url = reverse_lazy('accounts:user_password_reset_complete')

class UserPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'accounts/user_password_reset_complete.html'


class UserEditView(LoginRequiredMixin, UpdateView):
    template_name = 'accounts/user_edit.html'
    model = User
    form_class = UserEditForm


    def form_valid(self,form):
        messages.success(self.request, 'Update successfully done.')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('accounts:user_edit', kwargs={'pk': self.request.user.id})

templates/accounts/user_create_complate.html
{% extends 'base.html' %}

{% block content %}

<h2>You have completed your registration.</h2>
<p><a href="{% url 'accounts:user_login' %}">Login</a></p>

{% endblock %}

templates/accounts/user_create_done.html
{% extends 'base.html' %}

{% block content %}

<h2>Provisional registration</h2>

<p>Thank you for creation of an account.</p>
<p>You have not completed your registration yet. </p>
<p>Please confirm your email address to complete your registration. </p>
<p>If you don't receive the email, please check your spam or junk folders. </p>

{% endblock %}

templates/accounts/user_create_failed.html
{% extends 'base.html' %}

{% block content %}

An error has occurred.
{% for error_message in error_messages %}
{{ error_message }}
{% endfor %}

<p><a href="{% url 'accounts:user_regist' %}">Sign Up</a></p>

{% endblock %}

templates/accounts/user_edit.html
{% extends 'base.html' %}

{% block title %}
regist - {{ block.super }}
{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/user_edit.css' %}">

<div class="regist-wrapper">
    <div class="regist">
        {% if messages %}
            {% for message in messages %}
                <p class="update-message">{{ message }}</p>
            {% endfor %}
        {% endif %}
        <h3>User Info Setting</h3>

        <form method="POST" class="regist-form">
            {% csrf_token %}
            <div class="error-message">
                {{ form.non_field_errors }}
                {% if form.errors %}
                    {% for key, value in form.errors.items %}
                        {% if key != '__all__' %}
                            <p>{{ value }}</p>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>

            <div class="form-content">{{ form.email }}</div>
            <div class="form-content">
                <p class="country-label">Your country</p>
                {{ form.country }}
            </div>
            <input class="btn-regist" type="submit" value="Save">
        </form>

    </div>
</div>


{% endblock %}

templates/accounts/user_login.html
{% extends 'base.html' %}

{% block title %}
login - {{ block.super }}
{% endblock %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/user_login.css' %}">

<div class="login-wrapper">
    <div class="login">
        <h3>Login</h3>

        <form method="POST" class="login-form">
            {% csrf_token %}
            <div class="error-message">
            {{ form.non_field_errors }}
                {% if form.errors %}
                    {% for key, value in form.errors.items %}
                        {% if key != '__all__' %}
                            <p>{{ value }}</p>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>

            <div class="form-content">{{ form.username }}</div>
            <div class="form-content">{{ form.password }}</div>
            <div class="form-content">{{ form.remember.label }} {{ form.remember }}</div>
            <input class="btn-login" type="submit" value="Login">

            <div class="others-btn">
                <a class="btn user-regist-btn" href="{% url 'accounts:user_regist' %}">Sign Up</a>
                <a class="btn forget-password-btn" href="{% url 'accounts:user_password_reset' %}">Forgot Password</a>
            </div>

        </form>
    </div>

</div>

{% endblock %}

templates/accounts/user_password_reset.html
{% extends 'base.html' %}

{% block title %}
passwordsetting - {{ block.super }}
{% endblock %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/user_password_reset.css' %}">

<div class="password-reset-wrapper">
    <div class="password-reset">

        <form method="POST" class="password-reset-form">
            {% csrf_token %}
            <div class="error-message">
            {{ form.non_field_errors }}
                {% if form.errors %}
                    {% for key, value in form.errors.items %}
                        {% if key != '__all__' %}
                            <p>{{ value }}</p>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>

            <div class="form-content">
                <p>Please input your e-mail address.</p>
                {{ form.email }}
            </div>
            <input class="btn-password-reset" type="submit" value="submit">

        </form>



    </div>

</div>

{% endblock %}

templates/accounts/user_password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<p>You have completed password setting.</p>
<a href="{% url 'accounts:user_login' %}">Login</a>
{% endblock %}

templates/accounts/user_password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}
passwordsetting - {{ block.super }}
{% endblock %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/user_password_reset_confirm.css' %}">

<div class="password-reset-confirm-wrapper">
    <div class="password-reset">

        <form method="POST" class="password-reset-confirm-form">
            {% csrf_token %}
            <div class="error-message">
            {{ form.non_field_errors }}
                {% if form.errors %}
                    {% for key, value in form.errors.items %}
                        {% if key != '__all__' %}
                            <p>{{ value }}</p>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>

            <div class="form-content">
                <p>{{ form.new_password1.label }}:</p>
                {{ form.new_password1 }}
            </div>
            <div class="form-content">
                <p>{{ form.new_password2.label }}:</p>
                {{ form.new_password2 }}
            </div>
            <input class="btn-password-reset-confirm" type="submit" value="Regist">

        </form>



    </div>

</div>

{% endblock %}

templates/accounts/user_password_reset_done.html
{% extends "base.html" %}
{% block content %}
<p>
    We have sent you an email for resetting password.<br>
    Please reset your password from the URL on your email.
</p>
{% endblock %}

templates/accounts/user_regist.html
{% extends 'base.html' %}

{% block title %}
regist - {{ block.super }}
{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/user_regist.css' %}">


<div class="regist-wrapper">
    <div class="regist">
        <h3>Welcome! Please Sign Up!</h3>

        <form method="POST" class="regist-form">
            {% csrf_token %}
            <div class="error-message">
                {{ form.non_field_errors }}
                {% if form.errors %}
                    {% for key, value in form.errors.items %}
                        {% if key != '__all__' %}
                            <p>{{ value }}</p>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>

            <div class="form-content">{{ form.email }}</div>
            <div class="form-content">{{ form.password }}</div>
            <div class="form-content">{{ form.confirm_password }}</div>
            <div class="form-content">
                <p class="country-label">Your country</p>
                {{ form.country }}
            </div>
            <input class="btn-regist" type="submit" value="Sign Up">
            <br><br>
            <a href="{% url 'accounts:user_login' %}">Login Page</a>

        </form>

    </div>
</div>


{% endblock %}