accounts/urls.py
from django.urls import path

from .views import (
    UserPasswordResetDoneView, UserRegistView, UserCreateDoneView, UserCreateComplateView, UserLoginView,
    UserLogoutView, UserPasswordResetView, UserPasswordResetConfirmView, UserPasswordResetCompleteView, 
    UserEditView
)

app_name = 'accounts'

urlpatterns = [
    path('user_regist', UserRegistView.as_view(), name='user_regist'),
    path('user_create_done', UserCreateDoneView.as_view(), name='user_create_done'),
    path('user_create_complete/<token>', UserCreateComplateView.as_view(), name='user_create_complete'),
    path('user_login', UserLoginView.as_view(), name='user_login'),
    path('user_logout', UserLogoutView.as_view(), name='user_logout'),
    path('user_password_reset', UserPasswordResetView.as_view(), name='user_password_reset'),
    path('user_password_reset_done', UserPasswordResetDoneView.as_view(), name='user_password_reset_done'),
    path('user_password_reset_confirm/<uidb64>/<token>', UserPasswordResetConfirmView.as_view(), name='user_password_reset_confirm'),
    path('user_password_reset_complete', UserPasswordResetCompleteView.as_view(), name='user_password_reset_complete'),
    path('user_edit/<int:pk>', UserEditView.as_view(), name='user_edit'),
]

taskmanagement/urls.py
from django.urls import path

from .views import (
    HomeView, TaskCreateView, task_delete, TaskUpdateView, TaskConductView,
    task_record, MemoUpdateView, get_record, RecordCreateView, RecordUpdateView,
    record_delete, get_total_record, 
)

app_name = 'taskmanagement'

urlpatterns = [
    path('home', HomeView.as_view(), name='home'),
    path('task_create', TaskCreateView.as_view(), name='task_create'),
    path('task_delete', task_delete, name='task_delete'),
    path('task_update/<int:pk>', TaskUpdateView.as_view(), name='task_update'),
    path('task_conduct/<int:pk>', TaskConductView.as_view(), name='task_conduct'),
    path('task_record/', task_record, name='task_record'),
    path('update_memo/<int:pk>', MemoUpdateView.as_view(), name='update_memo'),
    path('get_record/', get_record, name='get_record'),
    path('record_create/', RecordCreateView.as_view(), name='record_create'),
    path('record_update/<int:pk>', RecordUpdateView.as_view(), name='record_update'),
    path('record_delete', record_delete, name='record_delete'),
    path('get_total_record', get_total_record, name='get_total_record'),
]

taskmanagement_project/urls.py
from django.contrib import admin
from django.urls import path, include

from taskmanagement import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('taskmanagement/', include('taskmanagement.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = views.page_not_found
handler500 = views.server_error

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Task Management{% endblock %}</title>
    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>

<body>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    <div class="main-wrapper"> 
        <div class="left-menu">
            <nav>
                <div class="logo">
                    <img class="logo-img" src="{% static 'images/logo.png' %}" alt="" width="200px">
                </div>
                {% if user.is_authenticated %}
                <ul class="main-nav">
                    <li><a href="{% url 'taskmanagement:home' %}" style="display:block; text-decoration:none; color:gray"><img style="margin-right: 10px;" src="{% static 'images/home.png' %}" width="20px">Dashboard</a></li>
                    <li><a href="{% url 'accounts:user_edit' pk=user.id %}" style="display:block; text-decoration:none; color:gray"><img style="margin-right: 10px;" src="{% static 'images/setting.png' %}" width="20px">Settings</a></li>
                    <li><a href="{% url 'accounts:user_logout' %}" style="display:block; text-decoration:none; color:gray"><img style="margin-right: 10px;" src="{% static 'images/logout.png' %}" width="20px">Logout</a></li>
                </ul>

                <ul class="main-nav-tab">
                    <li><a href="{% url 'taskmanagement:home' %}" style="display:block; text-decoration:none; color:gray"><img style="margin-right: 10px;" src="{% static 'images/home.png' %}" width="20px"></a></li>
                    <li><a href="{% url 'accounts:user_edit' pk=user.id %}" style="display:block; text-decoration:none; color:gray"><img style="margin-right: 10px;" src="{% static 'images/setting.png' %}" width="20px"></a></li>
                    <li><a href="{% url 'accounts:user_logout' %}" style="display:block; text-decoration:none; color:gray"><img style="margin-right: 10px;" src="{% static 'images/logout.png' %}" width="20px"></a></li>
                </ul>

                <div class="hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
                <nav class="globalMenuSp">
                      <ul>
                        <br><br><br>
                        <li style="margin-bottom: 20px;"><a href="{% url 'taskmanagement:home' %}" style="display:block; text-decoration:none;"><img style="margin-right: 10px; background:white" src="{% static 'images/home.png' %}" width="20px">Dashboard</a></li>
                        <li style="margin-bottom: 20px;"><a href="{% url 'accounts:user_edit' pk=user.id %}" style="display:block; text-decoration:none;"><img style="margin-right: 10px; background:white;" src="{% static 'images/setting.png' %}" width="20px">Settings</a></li>
                        <li><a href="{% url 'accounts:user_logout' %}" style="display:block; text-decoration:none; color:white"><img style="margin-right: 10px; background: white;" src="{% static 'images/logout.png' %}" width="20px">Logout</a></li>
                      </ul>
                </nav>

                {% endif %}
            </nav>
        </div>

        {% block content %}
        {% endblock %}
    </div>

    <script src="{% static 'js/base.js' %}"></script>
</body>

</html>