accounts/urls.py
from django.urls import path

from .views import (
    UserPasswordResetDoneView, UserRegistView, UserCreateDoneView, UserCreateComplateView, UserLoginView,
    UserLogoutView, UserPasswordResetView, UserPasswordResetConfirmView, UserPasswordResetCompleteView, 
    UserEditView
)

app_name = 'accounts'

urlpatterns = [
    path('user_regist', UserRegistView.as_view(), name='user_regist'),
    path('user_create_done', UserCreateDoneView.as_view(), name='user_create_done'),
    path('user_create_complete/<token>', UserCreateComplateView.as_view(), name='user_create_complete'),
    path('user_login', UserLoginView.as_view(), name='user_login'),
    path('user_logout', UserLogoutView.as_view(), name='user_logout'),
    path('user_password_reset', UserPasswordResetView.as_view(), name='user_password_reset'),
    path('user_password_reset_done', UserPasswordResetDoneView.as_view(), name='user_password_reset_done'),
    path('user_password_reset_confirm/<uidb64>/<token>', UserPasswordResetConfirmView.as_view(), name='user_password_reset_confirm'),
    path('user_password_reset_complete', UserPasswordResetCompleteView.as_view(), name='user_password_reset_complete'),
    path('user_edit/<int:pk>', UserEditView.as_view(), name='user_edit'),
]

taskmanagement/urls.py
from django.urls import path

from .views import (
    HomeView, TaskCreateView, task_delete, TaskUpdateView, TaskConductView,
    task_record, MemoUpdateView, get_record, RecordCreateView, RecordUpdateView,
    record_delete, get_total_record, 
)

app_name = 'taskmanagement'

urlpatterns = [
    path('home', HomeView.as_view(), name='home'),
    path('task_create', TaskCreateView.as_view(), name='task_create'),
    path('task_delete', task_delete, name='task_delete'),
    path('task_update/<int:pk>', TaskUpdateView.as_view(), name='task_update'),
    path('task_conduct/<int:pk>', TaskConductView.as_view(), name='task_conduct'),
    path('task_record/', task_record, name='task_record'),
    path('update_memo/<int:pk>', MemoUpdateView.as_view(), name='update_memo'),
    path('get_record/', get_record, name='get_record'),
    path('record_create/', RecordCreateView.as_view(), name='record_create'),
    path('record_update/<int:pk>', RecordUpdateView.as_view(), name='record_update'),
    path('record_delete', record_delete, name='record_delete'),
    path('get_total_record', get_total_record, name='get_total_record'),
]

taskmanagement_project/urls.py
from django.contrib import admin
from django.urls import path, include

from taskmanagement import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('taskmanagement/', include('taskmanagement.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = views.page_not_found
handler500 = views.server_error

taskmanagement/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator

User = get_user_model()


class TaskItems(models.Model):
    task_name = models.CharField(max_length=60)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE
    )
    color = models.CharField(max_length=50)
    

    class Meta:
        db_table = 'task_items'
        unique_together = ('task_name', 'user')

    def __str__(self):
        return f'{self.task_name}'


class TaskRecords(models.Model):
    time_total_second = models.IntegerField()
    time_min = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(59)])
    time_hour = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(23)])
    task = models.ForeignKey(
        TaskItems, on_delete=models.CASCADE
    )
    study_at_local = models.CharField(max_length=100)

    class Meta:
        db_table = 'task_records'

    def __str__(self):
        return f'{self.task.task_name}({self.time_total_second}s)'


class Memo(models.Model):
    memo = models.TextField(null=True, blank=True)
    user = models.OneToOneField(
        User, on_delete=models.CASCADE
    )

    class Meta:
        db_table = 'memo'
    
    def __str__(self):
        return f'{self.user.email}'

taskmanagement/forms.py
from django import forms
from bootstrap_datepicker_plus.widgets import DatePickerInput


from .models import TaskItems, Memo, TaskRecords


COLOR_CHOICES = (
    ('rgba(25, 247, 214)', 'LightGreen'),
    ('rgba(118, 118, 245)', 'LightBlue'),
    ('rgba(32, 54, 250)', 'Blue'),
    ('rgba(200, 130, 250)', 'Purple'),
    ('rgba(235, 199, 199)', 'Peach'),
    ('rgba(250, 76, 40)', 'Red'),
    ('rgba(247, 139, 7)', 'Orange'),
    ('rgba(252, 3, 227)', 'Pink'),
)


class TaskCreateForm(forms.ModelForm):
    task_name = forms.CharField(label='Task Title')
    color = forms.ChoiceField(choices=COLOR_CHOICES)

    class Meta:
        model = TaskItems
        fields = ('task_name', 'color')

    def __init__(self, *args, **kwargs):
        super(TaskCreateForm, self).__init__(*args, **kwargs)
        self.fields['task_name'].widget.attrs['class'] = 'form-control'
        self.fields['color'].widget.attrs['class'] = 'form-color'
        self.fields['task_name'].widget.attrs['placeholder'] = str(self.fields['task_name'].label) + '*'
    

    def save(self, commit=False):
        item = super().save(commit=False)
        item.user = self.user
        item.save()
        return item


class TaskUpdateForm(forms.ModelForm):
    task_name = forms.CharField(label='Task Title')
    color = forms.ChoiceField(choices=COLOR_CHOICES)

    class Meta:
        model = TaskItems
        fields = ('task_name', 'color')

    def __init__(self, *args, **kwargs):
        super(TaskUpdateForm, self).__init__(*args, **kwargs)
        self.fields['task_name'].widget.attrs['class'] = 'form-control'
        self.fields['color'].widget.attrs['class'] = 'form-color'
        self.fields['task_name'].widget.attrs['placeholder'] = str(self.fields['task_name'].label) + '*'


class MemoUpdateForm(forms.ModelForm):
    # memo = forms.CharField(widget=forms.Textarea(attrs={'cols':'80', 'rows': '10'}), required=False)
    memo = forms.CharField(widget=forms.Textarea(), required=False)

    def __init__(self, *args, **kwargs):
        super(MemoUpdateForm, self).__init__(*args, **kwargs)
        self.fields['memo'].widget.attrs['class'] = 'form-control'
        

    class Meta:
        model = Memo
        fields = ('memo', )
    


class RecordCreateForm(forms.ModelForm):
    time_hour = forms.IntegerField()
    time_min = forms.IntegerField()

    class Meta:
        model = TaskRecords
        fields = ('task', 'time_hour', 'time_min')

    def __init__(self, *args, **kwargs):
        super(RecordCreateForm, self).__init__(*args, **kwargs)
        self.fields['task'].widget.attrs['class'] = 'form-control'
        self.fields['time_hour'].widget.attrs['class'] = 'form-color'
        self.fields['time_min'].widget.attrs['class'] = 'form-color'
        


    def save(self, commit=False):
        record = super().save(commit=False)
        
        time_min = self.cleaned_data['time_min']
        time_hour = self.cleaned_data['time_hour']
        time_total_second = time_hour*3600 + time_min*60
        
        record.time_total_second = time_total_second
        record.save()
        return record


class RecordUpdateForm(forms.ModelForm):
    time_hour = forms.IntegerField()
    time_min = forms.IntegerField()

    class Meta:
        model = TaskRecords
        fields = ('task', 'time_hour', 'time_min')

    def __init__(self, *args, **kwargs):
        super(RecordUpdateForm, self).__init__(*args, **kwargs)
        self.fields['task'].widget.attrs['class'] = 'form-control'
        self.fields['time_hour'].widget.attrs['class'] = 'form-color'
        self.fields['time_min'].widget.attrs['class'] = 'form-color'

    
    def save(self, commit=False):
        record = super().save(commit=False)
        time_min = self.cleaned_data['time_min']
        time_hour = self.cleaned_data['time_hour']
        time_total_second = time_hour*3600 + time_min*60    
        record.time_total_second = time_total_second
        record.save()
        return record

taskmanagement/views.py
import json
import pytz
from django.utils import timezone
from django.db import IntegrityError
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.http.response import Http404, JsonResponse

from taskmanagement.models import TaskItems, TaskRecords, Memo
from .forms import (
    TaskCreateForm, TaskUpdateForm, MemoUpdateForm, RecordCreateForm,
    RecordUpdateForm,
)
from .utils import one_subject_record, all_subject_record


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = 'taskmanagement/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        tasks = TaskItems.objects.filter(
            user=user, 
        ).all()
        task_length = len(tasks)
        memo = get_object_or_404(Memo, user=self.request.user)

        task_records = TaskRecords.objects.filter(
            task__user=user,
        ).order_by('-study_at_local')[:7]
        
        all_record = all_subject_record(user, 7)

        context = {
            'tasks': tasks,
            'task_length': task_length,
            'memo': memo,
            'task_records': task_records,
            'data' : json.dumps(all_record),
        }

        return context
    


class TaskCreateView(LoginRequiredMixin, CreateView):
    template_name = 'taskmanagement/task_create.html'
    model = TaskItems
    form_class = TaskCreateForm
    success_url = reverse_lazy('taskmanagement:home')

    def get(self, request, *args, **kwargs):
        tasks = TaskItems.objects.filter(
            user=self.request.user
        ).all()
        if(len(tasks)) >= 8:
            return redirect('taskmanagement:home')
        else:
            return super().get(request, *args, **kwargs)


    def form_valid(self, form):
        try:
            form.user = self.request.user
            return super().form_valid(form)
        except IntegrityError:
            form.add_error('task_name', 'The title already exsists')
            return render(self.request, 'tasks/task_create.html', context={
                'form': form,
            })


@login_required
def task_delete(request):
    if request.method == "POST":
        task_id = request.POST['task_id']
        if task_id:
            task = get_object_or_404(TaskItems, pk=task_id, user=request.user.id)
            task.delete()
            return redirect(reverse_lazy('taskmanagement:home'))
        
        else:
            return redirect('taskmanagement:home')
    
    raise Http404


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'taskmanagement/task_update.html'
    model = TaskItems
    form_class = TaskUpdateForm
    success_url = reverse_lazy('taskmanagement:home')



class TaskConductView(LoginRequiredMixin, TemplateView):
    template_name = 'taskmanagement/task_conduct.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task = get_object_or_404(TaskItems, pk=kwargs.get('pk'), user=self.request.user)
        context['task'] = task
        return context


def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

@login_required
def task_record(request):
    if request.method == 'POST':
        record = request.POST.get('record')
        task_id = int(request.POST.get('task_id'))
        time_hour = int(record[:2])
        time_min = int(record[3:5])
        time_total_second = int(record[:2])*3600 + int(record[3:5])*60 + int(record[6:])
        now_utc = timezone.now()
        user = request.user
        now_local = now_utc.astimezone(pytz.timezone(user.country))
        TaskRecords.objects.create(
            time_total_second = time_total_second,
            time_min = time_min,
            time_hour = time_hour,
            task_id=task_id,
            study_at_local=now_local.date(),
        )

        if is_ajax(request=request):
            return JsonResponse({})


class MemoUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'taskmanagement/update_memo.html'
    model = Memo
    form_class = MemoUpdateForm
    success_url = reverse_lazy('taskmanagement:home')


@login_required
def get_record(request):
    if request.method == 'POST':
        task_id = request.POST['task_id']
        offset = int(request.POST['offset'])
        user = request.user
        data = one_subject_record(user, task_id, offset)

    if is_ajax(request=request):
        return JsonResponse({'data': data}, safe=False)
    


class RecordCreateView(LoginRequiredMixin, CreateView):
    template_name = 'taskmanagement/record_create.html'
    form_class = RecordCreateForm
    model = TaskRecords
    success_url = reverse_lazy('taskmanagement:home')

    def form_valid(self, form):
        study_at_local = self.request.POST.get('study_at_local')
        form.instance.study_at_local = study_at_local
        form.save()
        return super(RecordCreateView, self).form_valid(form)



class RecordUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'taskmanagement/record_update.html'
    model = TaskRecords
    form_class = RecordUpdateForm
    success_url = reverse_lazy('taskmanagement:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task_record = get_object_or_404(TaskRecords, pk=self.kwargs['pk'], task__user=self.request.user)
        context['task_record'] = task_record
        return context

    def form_valid(self, form):
        study_at_local = self.request.POST.get('study_at_local')
        form.instance.study_at_local = study_at_local
        form.save()
        return super(RecordUpdateView, self).form_valid(form)


@login_required
def record_delete(request):
    if request.method == "POST":
        task_record_id = request.POST['task_record_id']
        if task_record_id:
            task = get_object_or_404(TaskRecords, pk=task_record_id, task__user=request.user.id)
            task.delete()
            return redirect(reverse_lazy('taskmanagement:home'))
        
        else:
            return redirect('taskmanagement:home')
    
    raise Http404


@login_required
def get_total_record(request):
    if request.method == 'POST':
        offset = int(request.POST['offset'])
        user = request.user
        data = all_subject_record(user, offset)

    if is_ajax(request=request):
        return JsonResponse({'data': data}, safe=False)


# 404error
def page_not_found(request, exception):
    return render(request, '404.html', status=404)


def server_error(request):
    return render(request, '500.html', status=500)

templates/taskmanagement/_sidebar.html
{% load static %}

<div class="left-menu">
    <nav>
        <div class="logo">
            <img src="{% static 'images/logo.png' %}" alt="" width="200px">
        </div>
        <ul class="main-nav">
            <li><a href="{% url 'taskmanagement:home' %}" style="display:block; text-decoration:none; color:gray"><img style="margin-right: 10px;" src="{% static 'images/home.png' %}" width="20px">Dashboard</a></li>
            <li><a href="{% url 'accounts:user_edit' pk=user.id %}" style="display:block; text-decoration:none; color:gray"><img style="margin-right: 10px;" src="{% static 'images/setting.png' %}" width="20px">Settings</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:user_logout' %}" style="display:block; text-decoration:none; color:gray"><img style="margin-right: 10px;" src="{% static 'images/logout.png' %}" width="20px">Logout</a></li>
            {% endif %}
        </ul>
    </nav>
</div>

templates/taskmanagement/home.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">


<div class="main-contents">
    <h2 class="main-title">Dashboard</h2>

    <div class="main-upper">

        <div class="title-wapper">
            <h3 class="task-list">
                <img src="{% static 'images/checkicon.png' %}" width="15px">
                Task List
            </h3>
            {% if task_length < 8 %}
                <a href="{% url 'taskmanagement:task_create' %}"><button class="create-btn"> +Create</button></a>
            {% else %}
                <button class="create-btn">Max 8items</button>
            {% endif %}
        </div>

        <div class="container">
            {% for task in tasks %}
                <div class="item" name="{{ task.id }}" value="{{ task.task_name }}" style="border: 2px solid {{ task.color }};">
                    <span class="item-name">{{ task.task_name | truncatechars:30 }}</span>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="main-lower">

        <div class="title-wapper">
            <h3 style="color:darkblue">
                <img src="{% static 'images/checkicon.png' %}" width="15px">
                Recent Record
            </h3>
            <a href="{% url 'taskmanagement:record_create' %}"><button class="create-btn">+Create</button></a>
        </div>

        <div class="table-wrap">
            <table class="recent-record-table" border="1">
                    <tr>
                        <th>Task</th>
                        <th>Date</th>
                        <th>Record</th>
                        <th></th>
                    </tr>
                    {% for task_record in task_records %}
                    <tr>
                        <td>{{ task_record.task.task_name }}</td>
                        <td>{{ task_record.study_at_local }}</td>
                        {% if task_record.time_hour == 0 %}
                            <td>{{ task_record.time_min }}m</td>
                        {% else %}
                            <td>{{ task_record.time_hour }}h{{ task_record.time_min }}m</td>
                        {% endif %}
                        <td>
                            <a href="{% url 'taskmanagement:record_update' task_record.id %}"><button class="edit-btn">Edit</button></a>
                            <button type="submit" class="record-delete-btn" value="{{ task_record.id }}">Delete</button>
                        </td>
                        
                    </tr>
                    {% endfor %}
            </table>
        </div>

    </div>
</div>

<div class="right-menu">
    <div class="right-upper">
        <h4 class="memo-title" style="color: darkblue;">Memo</h4>
        <a href="{% url 'taskmanagement:update_memo' memo.pk %}"><button class="create-btn memo-btn">+Create</button></a>
        <div class="memo">
            {% if memo.memo != None %}
                {{ memo.memo | linebreaksbr }}
            {% endif %}
        </div>
    </div>

    <div class="right-lower">
        <h4 class="total-record-title" style="color: darkblue;">TotalRecord</h4>
        <div class="period-btn-wrapper-total">
            <button class="period-btn-total btn-active" value="7">1week</button>
            <button class="period-btn-total" value="30">1month</button>
            <button class="period-btn-total" value="90">3months</button>
        </div>
        <div class="canvas-container-integrated">
            <canvas id="my_chart_integrated">Canvas Not supported</canvas>
        </div>    
    </div>
</div>

<script src="{% static 'js/home.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"></script>

<!-- グラフモーダル -->
<div id="overlay" class="overlay"></div>
<div class="modal-window">
    <span class="close-btn">×</span>

    <div class="task-menu">

        <div class="task-btn">
            <a id="task-edit-btn" href="">Task Edit</a>
            <button id="task-delete-btn" class="task-delete-btn">Task Delete</button>
        </div>

        <div class="period-btn-wrapper">
            <button class="period-btn btn-active" value="7">1week</button>
            <button class="period-btn" value="30">1month</button>
            <button class="period-btn" value="90">3months</button>
            <button class="period-btn" value="180">6months</button>
            <button class="period-btn" value="365">1year</button>
        </div>

    </div>
    
    <div class="canvas-container">
        <canvas id="my_chart">Canvas Not supported</canvas>
    </div>    
    <a id="task-start-btn" href="" class="btnarrow4">Task Start</a>

</div>

<!-- デリート確認モーダル(タスク用) -->
<div id="delete-modal-wrapper" class="delete-modal-wrapper">
    <div class="delete-modal">
        <p class="task-title"></p>
        <hr class="hr-modal">
        <p>
        Is is all right to delete this task completely?<br>
        (The record will also be deleted.)
        </p>
        <div class="delete-modal-btn">
            <form action="{% url 'taskmanagement:task_delete' %}" method="POST" class="form-delete">
                {% csrf_token %}
                <input id="hidden-delete" type="hidden" name="task_id" value="">
                <button type="submit" class="modal-btn delete-btn">Delete</button>
            </form>
            <button type="button" class="modal-btn cancel-btn">Cancel</button>
        </div>
    </div>
</div>


<!-- デリート確認モーダル(レコード用) -->
<div id="delete-record-modal-wrapper" class="delete-modal-wrapper">
    <div class="delete-modal">
        <p class="task-title"></p>
        <hr class="hr-modal">
        <p>
        Is is all right to delete this task record?<br>
        </p>
        <div class="delete-modal-btn">
            <form action="{% url 'taskmanagement:record_delete' %}" method="POST" class="form-delete">
                {% csrf_token %}
                <input id="hidden-record-delete" type="hidden" name="task_record_id" value="">
                <button type="submit" class="modal-btn delete-btn">Delete</button>
            </form>
            <button type="button" class="modal-btn cancel-btn" id="delete-record-cancel-btn">Cancel</button>
        </div>
    </div>
</div>


<!-- スマホ用ナビゲーションメニュー -->
<div class="hamburger">
    <span></span>
    <span></span>
    <span></span>
</div>
<nav class="globalMenuSp">
      <ul>
        <br><br><br>
        {% if user.is_authenticated %} 
            <li style="margin-bottom: 20px;"><a href="{% url 'taskmanagement:home' %}" style="display:block; text-decoration:none;"><img style="margin-right: 10px; background:white" src="{% static 'images/home.png' %}" width="20px">Dashboard</a></li>
            <li style="margin-bottom: 20px;"><a href="{% url 'accounts:user_edit' pk=user.id %}" style="display:block; text-decoration:none;"><img style="margin-right: 10px; background:white;" src="{% static 'images/setting.png' %}" width="20px">Settings</a></li>
            <li><a href="{% url 'accounts:user_logout' %}" style="display:block; text-decoration:none; color:white"><img style="margin-right: 10px; background: white;" src="{% static 'images/logout.png' %}" width="20px">Logout</a></li>
        {% endif %}
      </ul>
</nav>

<input name="csrfToken" value="{{ csrf_token }}" type="hidden">


<script>
    (function() {
        'user strict';

        const data_js = JSON.parse('{{ data | safe }}');

        var type = 'bar';
        
        var data = data_js;
        
        var options = {
            animation: {
                duration: 1000,
            },
            legend: {
                display: false
            },
            scales: {
                xAxes: [{
                    ticks: {
                        fontColor: "black",
                        fontSize: 12,
                        callback: function(value, index, values){
                            return [value.substr(5,2) + '/' + value.substr(8,2)]
                        },
                    },
                    gridLines: {
                        color: 'rgba(48, 48, 47, 0.3)',
                    },
                    stacked: true
                }],
                yAxes: [{
                    stacked: true,
                    ticks: {
                        fontColor: "black",
                        fontSize: 10,
                        suggestedMin: 0,
                        suggestedMax: 1800,
                        stepSize: 3600,
                        callback: function(value, index, values){
                            return String(value / 3600) + 'hours'
                        },
                    },
                    gridLines: {
                        color: 'rgba(48, 48, 47, 0.3)',
                    },
                }],
            },
            tooltips: {
                mode: 'label',
                callbacks: {
                    label: function(tooltipItem, data){
                        let value = tooltipItem.value;
                        let index = tooltipItem.datasetIndex;
                        let label = data.datasets[index].label;
                        if (String(Math.floor(value / 3600))==0 && String(Math.floor(value%3600/60))==0) {
                            return undefined;
                        }
                        else {
                            return label + ':' + String(Math.floor(value / 3600)) + 'hour' + ' ' + String(Math.floor(value%3600/60)) + 'min';
                        }
                    }
                }
            },
            responsive: true,
            maintainAspectRatio: false,
        };

        var ctx = document.getElementById('my_chart_integrated').getContext('2d');
        var myChart = new Chart(ctx, {
            type: type,
            data: data,
            options: options,
        });

        $('.period-btn-total').click(function () {
            $('.period-btn-total').removeClass('btn-active');
            $(this).addClass('btn-active');
            var offset = $(this).val()
    
            // グラフ用の必要情報取得Ajax
            var token = $('input[name="csrfToken"]').attr('value');
            $.ajaxSetup({
                beforeSend: function(xhr){
                    xhr.setRequestHeader('X-CSRFToken', token);
                }
            })
            $.ajax({
                type: "POST",
                url: "{% url 'taskmanagement:get_total_record' %}",
                data: {
                    'offset': offset,
                },
                dataType: 'json',
                success: function(response){
                    var data = response.data
                    
                    $('#my_chart_integrated').remove();
                    $('.canvas-container-integrated').append("<canvas id='my_chart_integrated'></canvas>");
                    var ctx = document.getElementById('my_chart_integrated').getContext('2d');
                    var myChart = new Chart(ctx, {
                        type: type,
                        data: data,
                        options: options,
                    });
                }
            }); 
        });

    })();




</script>


{% endblock %}

templates/taskmanagement/record_create.html
{% extends 'base.html' %}

{% block title %}
recordcreate - {{ block.super }}
{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/record_create.css' %}">

<div class="task-create-wrapper">
    <div class="task-create">
        <h2>Create a New Task</h2>
        <p>Please Input a title and choose a color (used for graph).</p>

        <form method="POST" class="task-create-form">
            {% csrf_token %}

            {{ form.non_field_errors }}
            {% if form.errors %}
                {% for key, value in form.errors.items %}
                    {% if key != '__all__' %}
                        <p>{{value.as_text}}</p>
                    {% endif %}
                {% endfor %}
            {% endif %}

            <div class="form-wrapper">
                Task:{{ form.task }}<br>
                Task Record:
                <span class="form-hour-min">
                    <span class="form-hour">
                    {{ form.time_hour }}hour</span>
                    <span class="form-min">
                    {{ form.time_min }}min</span>
                </span><br>
                Date:<input class="date-form" type="date" name="study_at_local" required>
            </div>
            <input class="btn-task-create" type="submit" value="Create">
            
            

        </form>

    </div>
</div>

{% endblock %}

templates/taskmanagement/record_update.html
{% extends 'base.html' %}

{% block title %}
recordcreate - {{ block.super }}
{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/record_create.css' %}">

<div class="task-create-wrapper">
    <div class="task-create">
        <h2>Create a New Task</h2>
        <p>Please Input a title and choose a color (used for graph).</p>

        <form method="POST" class="task-create-form">
            {% csrf_token %}

            {{ form.non_field_errors }}
            {% if form.errors %}
                {% for key, value in form.errors.items %}
                    {% if key != '__all__' %}
                        <p>{{value.as_text}}</p>
                    {% endif %}
                {% endfor %}
            {% endif %}

            <div class="form-wrapper">
                Task:{{ form.task }}<br>
                Task Record:
                <span class="form-hour-min">
                    <span class="form-hour">
                    {{ form.time_hour }}hour</span>
                    <span class="form-min">
                    {{ form.time_min }}min</span>
                </span><br>
                Date:<input class="date-form" type="date" name="study_at_local" required value="{{ task_record.study_at_local }}">
            </div>
            <input class="btn-task-create" type="submit" value="Update">
            
            

        </form>

    </div>
</div>

{% endblock %}

templates/taskmanagement/task_conduct.html
{% extends 'base.html' %}

{% block title %}
srudy_main - {{ block.super }}
{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/task_conduct.css' %}">

<div>
    <h2 class="task-title" name="{{ task.id }}">{{ task.task_name }}</h2>
    <div class="container">
        <div id="timer">00:00:00</div>
        <div class="controls">
            <div class="btn" id="start">Start</div>
            <div class="btn" id="stop">Stop</div>
            <div class="btn" id="reset">Reset</div>
            <div class="btn btn-record" id="record">Record</div>
        </div>
        <input name="csrfToken" value="{{ csrf_token }}" type="hidden">
    </div>
</div>

<div id="loading-modal" class="loading-modal">
    <canvas width="150px" height="150px">
        Canvas Not supported
    </canvas>
</div>

<div id="success-modal-wrapper" class="success-modal-wrapper">
    <div class="success-modal">
        Record has been completed.<br>
        Good Job.<br>
        <div style="text-align:right;"><a href="{% url 'taskmanagement:home' %}">Home</a></div>
    </div>
</div>

<script src="{% static 'js/task_conduct.js' %}"></script>

{% endblock %}